### ISSUE TITLE
Organization of Meeting Summaries

### ISSUE THREAD

**Issue by SucrenSpice** [SingularityNet-Ambassador-Program/African-Guild#1]
https://app.dework.xyz/singularitynet-ambas/africa-guild?taskId=8b37647a-5ab9-44e2-b637-0cbe9e3b4c08

**Comment by frankchukwurah** [comment]
https://drive.google.com/drive/folders/14AQ5tTYu-ghd0Zz74qpja6tlbwRWCU2N
